version: "3.8"

services:  

  prometheus:
    image: prom/prometheus
    container_name: observability-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
   
  grafana:
    image: grafana/grafana
    container_name: observability-grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: observability-cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    
  redis:
    image: redis:latest
    container_name: observability-redis
    ports:
    - 6379:6379

  app:
    build: .
    container_name: observability-prometheus-app
    volumes:
      - .:/go/src
    ports:
      - 8181:8181